apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db-pod
  template:
    metadata:
      labels:
        app: postgres-db-pod
    spec:
      containers:
        - name: postgres-db-deployment
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: user_meteo
            - name: POSTGRES_PASSWORD
              value: password123!
            - name: POSTGRES_DB
              value: db_meteo
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-db-storage
          persistentVolumeClaim:
            claimName: postgres-db-pvc